In [3]:
import FinanceDataReader as fdr
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import timedelta
from time import sleep

def getCloseData(ticker, start, end=None):
    """
    종가 데이터
    ticker: 종목 번호
    start: 시작일
    end: 마지막 날짜
    return: 종목의 종가 데이터
    """
    return fdr.DataReader(ticker, start, end)['Close']

In [4]:
def updateDynamicDataSet():
    """
    자산배분데이터 최신화
    from datetime import timedelta
    from time import sleep
    """
    data = pd.read_csv("동적자산배분데이터.csv", index_col=0, parse_dates=True)
    tickers = data.columns

    start = data.index[-1]+timedelta(days=1)

    newDf = pd.DataFrame()

    for ticker in tickers:
        newData = getCloseData(ticker, start)
        newDf = pd.concat([newDf, newData], axis=1)
        sleep(3)

    newDf.columns = tickers
    newDf.index = pd.to_datetime(newDf.index)
    updatedData = pd.concat([data, newDf])
    updatedData.to_csv("동적자산배분데이터.csv")
    return updatedData

In [5]:
def updateStaticDataSet():
    """
    자산배분데이터 최신화
    from datetime import timedelta
    from time import sleep
    """
    data = pd.read_csv("정적자산배분데이터.csv", index_col=0, parse_dates=True)
    tickers = data.columns

    start = data.index[-1]+timedelta(days=1)

    newDf = pd.DataFrame()

    for ticker in tickers:
        newData = getCloseData(ticker, start)
        newDf = pd.concat([newDf, newData], axis=1)
        sleep(3)

    newDf.columns = tickers
    newDf.index = pd.to_datetime(newDf.index)
    updatedData = pd.concat([data, newDf])
    updatedData.to_csv("정적자산배분데이터.csv")
    return updatedData

In [6]:
updateDynamicDataSet()
updateStaticDataSet()

,VTI,VBR,TLT,IEF,IEI,SHY,GSG,GLD
2010-01-04,46.08189,55.52,66.13332,71.24535,94.21502,75.39010,32.70,109.80
2010-01-05,46.25879,55.46,66.56042,71.55817,94.51414,75.48085,33.03,109.70
2010-01-06,46.32312,55.55,65.66942,71.26941,94.38595,75.48993,33.27,111.51
2010-01-07,46.51610,56.04,65.77987,71.26941,94.35176,75.47178,33.11,110.82
2010-01-08,46.66887,56.24,65.75042,71.35764,94.48850,75.54438,33.18,111.37
...,...,...,...,...,...,...,...,...
2022-06-27,194.59000,154.32,111.60000,100.58000,118.16000,82.55000,23.94,169.90
2022-06-28,190.58000,152.64,112.12000,100.71000,118.17000,82.53000,24.23,169.62
2022-06-29,190.26000,150.95,113.87000,101.52000,118.71000,82.63000,23.79,169.49
2022-06-30,188.62000,149.82,114.87000,102.30000,119.34000,82.79000,23.10,168.46
2022-07-01,190.61000,151.94,115.82000,103.24000,120.21000,82.96000,23.38,168.32