In [2]:
import FinanceDataReader as fdr
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

def getCloseData(ticker, start, end=None):
    """
    종가 데이터
    ticker: 종목 번호
    start: 시작일
    end: 마지막 날짜
    return: 종목의 종가 데이터
    """
    return fdr.DataReader(ticker, start, end)['Close']

def getDayReturn(closeDataSet):
    """
    개별종목 일별 수익률
    closeDataSet: 종가 데이터
    return: 종가 데이터의 일별 수익률
    """
    return (closeDataSet / closeDataSet.shift(1)).fillna(1)

def getCumulativeReturn(closeDataSet):
    """
    개별종목 누적수익률 == 자산흐름
    closeDataSet: 종가 데이터
    return:종가데이터 누적수익률
    """
    return closeDataSet / closeDataSet.iloc[0]

def getPortfolioResult(closeDataSet, weight=None):
    """
    포트폴리오 결과
    closeDataSet: 종가 데이터
    weight: 포트폴리오 개별자산 비중
    return: 포트폴리오 일간수익률, 누적수익률
    """
    # 개별종목 일별 수익률
    dayReturn = getDayReturn(closeDataSet)
    # 개별종목 누적 수익률
    cumulativeReturn = getCumulativeReturn(closeDataSet)
    # 자산별 비중. 기본값: 동일비중
    if not weight:
        weight = [1/len(closeDataSet.columns)] * len(closeDataSet.columns)
        
    # 포트폴리오 누적 수익률
    portfolioCumulativeReturn = (weight * cumulativeReturn).sum(axis=1)
    # 포트폴리오 일별 수익률
    portfolioDayReturn = (portfolioCumulativeReturn / portfolioCumulativeReturn.shift(1)).fillna(1)    
    return portfolioDayReturn, portfolioCumulativeReturn

def getEvaluation(cumulativeReturn):
    """
    cagr, dd, mdd
    투자 성과 지표
    """
    # cagr
    cagr = cumulativeReturn.iloc[-1] ** (252/len(cumulativeReturn))
    # mdd
    dd = (cumulativeReturn.cummax() - cumulativeReturn) / cumulativeReturn.cummax() * 100
    mdd= dd.max()
    
    print(f"최종 수익률: {cumulativeReturn.iloc[-1]}\ncagr: {cagr}\nmdd: {mdd}")

    return cagr, dd, mdd

def getRebalancingDate(closeDataSet, period="month"):
    """
    리밸런싱 일자 추출
    월별, 분기별, 연별
    """
    data = closeDataSet.copy()
    data = pd.DataFrame(data)
    data.index = pd.to_datetime(data.index)
    data['year'] = data.index.year
    data['month'] = data.index.month
    
    if period == "month":
        rebalancingDate = data.drop_duplicates(['year', 'month'], keep="last").index
        
    if period == "quarter":
        # 3 6 9 12월 말에 리밸런싱
        # np where 같은걸로 3, 6, 9, 12월 데이터만 가져오고
        # drop_duplicates keep last 하면 됌
        quarter = [3,6,9,12]
        data = data.loc[data['month'].isin(quarter)]
        rebalancingDate = data.drop_duplicates(['year', 'month'], keep="last").index
    
    if period == "year":
        rebalancingDate = data.drop_duplicates(['year'], keep="last").index
        
    return rebalancingDate

def getRebalancingPortfolioResult(closeDataSet, period = "month", weightDf=None):
    """
    리밸런싱 포트폴리오 결과
    closeDataSet: 종가 데이터
    weight: 포트폴리오 개별자산 비중
    return: 포트폴리오 일간수익률, 누적수익률
    """
    
    # 자산별 비중. 기본값: 동일비중
    if weightDf is None:
        rebalancingDate = getRebalancingDate(closeDataSet, period) # 리밸런싱 날짜
        weightDf = pd.DataFrame([[1/len(closeDataSet.columns)] * len(closeDataSet.columns)] * len(rebalancingDate),
                              index=rebalancingDate,
                              columns=closeDataSet.columns)
    else:
        rebalancingDate = weightDf.index # 리밸런싱 날짜
      
    portfolio = pd.DataFrame() # 빈 데이터 프레임 생성

    totalAsset = 1 # 총 자산, 초기값 1
    start = rebalancingDate[0] # 리밸런싱 날짜, 초기값 첫 투자일

    for end in rebalancingDate[1:]:
        weight = weightDf.loc[start] # 당월 리밸런싱 비율
        priceData = closeDataSet.loc[start:end] # 당월 가격 데이터
        cumReturn = getCumulativeReturn(priceData) # 당월 누적 수익률
        weightedCumReturn = weight * cumReturn # 당월 리밸런싱 비율이 반영된 누적 수익률
        netCumReturn = totalAsset * weightedCumReturn # 전월 투자 결과 반영

        start = end # start 갱신
        totalAsset = netCumReturn.iloc[-1].sum() # 총 자산 갱신
        portfolio = pd.concat([portfolio, netCumReturn]) # 매월 데이터 추가
    
    portfolio = portfolio.loc[~portfolio.index.duplicated(keep='last')] # 중복 데이터 제거
    portfolioCumulativeReturn = portfolio.sum(axis=1) # 포트폴리오 누적 수익률
    portfolioDayReturn = (portfolioCumulativeReturn / portfolioCumulativeReturn.shift(1)).fillna(1) # 포트폴리오 일간 수익률
    
    return portfolioDayReturn, portfolioCumulativeReturn

def getWeightByAvgMomentumScore(closeDataSet, n = 12):
    """
    평균 모멘텀 스코어를 기반으로 한 투자 비중 구하기
    closeDataSet: 종가 데이터
    n: 모멘텀 기간 1~n
    return: 투자비중 weight df, 평균모멘텀 스코어 df
    """
    avgMomentumScore = 0 # 평모스 초기값
    priceOnRebalDate = closeDataSet.loc[getRebalancingDate(closeDataSet)] # 리밸런싱 일자의 가격 데이터
    
    # 1 ~ n개월 모멘텀 스코어 합
    for i in range(1, n+1):
        avgMomentumScore = np.where(priceOnRebalDate / priceOnRebalDate.shift(i) > 1, 1, 0) + avgMomentumScore
        
    # 평모스 계산
    avgMomentumScore = pd.DataFrame(avgMomentumScore, index=priceOnRebalDate.index, columns=priceOnRebalDate.columns) # dataframe 형변환
    avgMomentumScore = avgMomentumScore / n
    
    # 모멘텀 스코어에 따른 weight 계산
    weight = avgMomentumScore.divide(avgMomentumScore.sum(axis=1), axis=0).fillna(0)
    # 투자 비중이 모두 0인 구간에서는 현금 보유
    weight['cash'] = np.where(weight.sum(axis=1) == 0, 1, 0)
    
    # 투자비중, 평모스 리턴
    return weight, avgMomentumScore

## 1. 실제 주식 매매 단위와 거래 수수료 반영

In [30]:
# 데이터 로드
stock = getCloseData("069500", "2002") # 코스피200 ETF
bond = getCloseData("152380", "2002") # kodex 국고채 10년물 etf

closeDataSet = pd.concat([stock, bond], axis=1)
closeDataSet.columns = ['stock', 'bond']
closeDataSet.dropna(inplace=True)
closeDataSet

            stock     bond
Date
2012-01-20  21744  49960.0
2012-01-25  21820  49960.0
2012-01-26  21841  49930.0
2012-01-27  21875  50000.0
2012-01-30  21628  50130.0
...           ...      ...
2022-08-02  32195  65140.0
2022-08-03  32420  64955.0
2022-08-04  32585  64910.0
2022-08-05  32800  65020.0
2022-08-08  32715  64710.0

[2597 rows x 2 columns]

In [31]:
# 리밸런싱 날짜
rebalancingDate = getRebalancingDate(closeDataSet)

# 리밸런싱 비율, 동일비중으로 가정
portfolioWeight = [0.5, 0.5]
weightDf = pd.DataFrame([portfolioWeight] * len(rebalancingDate), index=rebalancingDate, columns=closeDataSet.columns) 
weightDf

            stock  bond
Date
2012-01-31    0.5   0.5
2012-02-29    0.5   0.5
2012-03-30    0.5   0.5
2012-04-30    0.5   0.5
2012-05-31    0.5   0.5
...           ...   ...
2022-04-29    0.5   0.5
2022-05-31    0.5   0.5
2022-06-30    0.5   0.5
2022-07-29    0.5   0.5
2022-08-08    0.5   0.5

[128 rows x 2 columns]

In [114]:
totalAsset = 10000000 # 초기 자본금, 1000만원 가정
prevQuantity = 0 # 초기 자산 보유량

portfolio = pd.DataFrame() # 전체 자산흐름을 담을 데이터프레임
start = rebalancingDate[0] # 리밸런싱 날짜, 초기값 첫 투자일


for end in rebalancingDate[1:]:
    weight = weightDf.loc[start] # 당기 리밸런싱 비율
    
    capacity = totalAsset * weight # 리밸런싱 비율에 따른 자산별 가용액,
    
    priceData = closeDataSet.loc[start: end] # 당기 가격 데이터
    priceOnRebalDay = priceData.iloc[0] # 리밸런싱 당일 가격
       
    quantity = capacity // priceOnRebalDay # 이번달 capacity에 따라 실제 보유 해야 할 주식수
    
    diffQuantity = quantity - prevQuantity # 실제 매매해야하는 수량, 양수-> 매수, 음수 -> 매도
    fee = abs(diffQuantity) *  priceOnRebalDay * 0.0015 # 수수료, 0.15% => 0.0015
    
    leftCash = (capacity - quantity * priceOnRebalDay).sum() # 잔여 현금
    
    assetFlow = quantity * priceData # 수량*가격 = 각 자산 흐름   
    valueOnLastDay = assetFlow.iloc[-1].sum() # 월말 평가액
    
    assetFlow['leftCash'] = round(leftCash, 2)
    portfolio = pd.concat([portfolio, assetFlow]) # 데이터프레임에 추가
    
    # 슬리피지를 고려하고 싶다면 여기에 적당한 패널티를 부여할 것
    totalAsset = (valueOnLastDay + leftCash) - fee # (월말 평가액 + 잔여 현금 - 수수료) totalAsset 업데이트,,
    prevQuantity = quantity # 이전 자산 보유량 업데이트
    start = end # 리밸런싱 날짜 업데이트
    
portfolio

                stock       bond  leftCash
Date
2012-01-31  4979376.0  4967820.0  52804.00
2012-02-01  4985559.0  4972770.0  52804.00
2012-02-02  5041664.0  4967820.0  52804.00
2012-02-03  5016016.0  4968810.0  52804.00
2012-02-06  5023344.0  4961880.0  52804.00
...               ...        ...       ...
2022-08-02  7082900.0  7100260.0  75146.16
2022-08-03  7132400.0  7080095.0  75146.16
2022-08-04  7168700.0  7075190.0  75146.16
2022-08-05  7216000.0  7087180.0  75146.16
2022-08-08  7197300.0  7053390.0  75146.16

[2718 rows x 3 columns]

In [33]:
# 매달 마지막 영업일엔 리밸런싱이 들어간 row만 남긴다.
portfolio = portfolio.loc[~portfolio.index.duplicated(keep='last')]
portfolio

                stock       bond  leftCash
Date
2012-01-31  4979376.0  4967820.0  52804.00
2012-02-01  4985559.0  4972770.0  52804.00
2012-02-02  5041664.0  4967820.0  52804.00
2012-02-03  5016016.0  4968810.0  52804.00
2012-02-06  5023344.0  4961880.0  52804.00
...               ...        ...       ...
2022-08-02  7082900.0  7100260.0  75146.16
2022-08-03  7132400.0  7080095.0  75146.16
2022-08-04  7168700.0  7075190.0  75146.16
2022-08-05  7216000.0  7087180.0  75146.16
2022-08-08  7197300.0  7053390.0  75146.16

[2592 rows x 3 columns]

In [34]:
# 포트폴리오 자산흐름
portfolioAssetFlow = portfolio.sum(axis=1)
portfolioAssetFlow

Date
2012-01-31    10000000.00
2012-02-01    10011133.00
2012-02-02    10062288.00
2012-02-03    10037630.00
2012-02-06    10038028.00
                 ...
2022-08-02    14258306.16
2022-08-03    14287641.16
2022-08-04    14319036.16
2022-08-05    14378326.16
2022-08-08    14325836.16
Length: 2592, dtype: float64

In [35]:
# 누적 수익률
cumReturn = portfolioAssetFlow / portfolioAssetFlow.iloc[0]
cumReturn

Date
2012-01-31    1.000000
2012-02-01    1.001113
2012-02-02    1.006229
2012-02-03    1.003763
2012-02-06    1.003803
                ...
2022-08-02    1.425831
2022-08-03    1.428764
2022-08-04    1.431904
2022-08-05    1.437833
2022-08-08    1.432584
Length: 2592, dtype: float64

In [42]:
# 수수료 고려
_,_,_ = getEvaluation(cumReturn)

최종 수익률: 1.432583616
cagr: 1.0355673073378828
mdd: 20.7089925830455

In [37]:
# 수수료 고려 X

_, cumReturnWithoutFee = getRebalancingPortfolioResult(closeDataSet=closeDataSet, weightDf=weightDf)
_,_,_ = getEvaluation(cumReturnWithoutFee)

최종 수익률: 1.4382834369444089
cagr: 1.0359671659050578
mdd: 20.75428106156669

## 2. 함수화

In [148]:
def getRebalPortResultWithFee(closeDataSet, totalAsset, period = "month", weightDf=None):
    
    # 자산별 비중. 기본값: 동일비중
    if weightDf is None:
        rebalancingDate = getRebalancingDate(closeDataSet, period) # 리밸런싱 날짜
        weightDf = pd.DataFrame([[1/len(closeDataSet.columns)] * len(closeDataSet.columns)] * len(rebalancingDate),
                              index=rebalancingDate,
                              columns=closeDataSet.columns)
    else:
        rebalancingDate = weightDf.index # 리밸런싱 날짜
    
    totalAsset = totalAsset # 초기 자본금
    prevQuantity = 0 # 초기 자산 보유량
    
    quantityDf = pd.DataFrame() # 시기별 각 자산 보유량을 담을 데이터프레임
    portfolio = pd.DataFrame() # 전체 자산흐름을 담을 데이터프레임
    
    
    start = rebalancingDate[0] # 리밸런싱 날짜, 초기값 첫 투자일

    for end in rebalancingDate[1:]:
        weight = weightDf.loc[start] # 당기 리밸런싱 비율

        capacity = totalAsset * weight # 리밸런싱 비율에 따른 자산별 가용액,

        priceData = closeDataSet.loc[start: end] # 당기 가격 데이터
        priceOnRebalDay = priceData.iloc[0] # 리밸런싱 당일 가격

        quantity = capacity // priceOnRebalDay # 이번달 capacity에 따라 실제 보유 해야 할 주식수
        diffQuantity = quantity - prevQuantity # 실제 매매해야하는 수량, 양수-> 매수, 음수 -> 매도
        fee = abs(diffQuantity) *  priceOnRebalDay * 0.0015 # 수수료, 0.15% => 0.0015

        leftCash = (capacity - quantity * priceOnRebalDay).sum() # 잔여 현금

        assetFlow = quantity * priceData # 수량*가격 = 각 자산 흐름   
        valueOnLastDay = assetFlow.iloc[-1].sum() # 월말 평가액

        assetFlow['leftCash'] = round(leftCash, 2)
        portfolio = pd.concat([portfolio, assetFlow]) # 자산 흐름 데이터프레임에 추가
        quantityDf = quantityDf.append([quantity]) # 자산 보유량 데이터프레임에 추가

        # 슬리피지를 고려하고 싶다면 여기에 적당한 패널티를 부여할 것
        totalAsset = (valueOnLastDay + leftCash) - fee # (월말 평가액 + 잔여 현금 - 수수료) totalAsset 업데이트,,
        prevQuantity = quantity # 이전 자산 보유량 업데이트
        
        print(start, end)
        
        start = end # 리밸런싱 날짜 업데이트
        
    # quantityDf 인덱스 설정
    quantityDf.index = rebalancingDate[:-1]
    # 매달 마지막 영업일엔 리밸런싱이 들어간 row만 남긴다.
    portfolio = portfolio.loc[~portfolio.index.duplicated(keep='last')]
    # 포트폴리오 자산흐름
    portfolioAssetFlow = portfolio.sum(axis=1)
    # 누적 수익률
    cumReturn = portfolioAssetFlow / portfolioAssetFlow.iloc[0]
    # 일간 수익률
    dayReturn = (cumReturn / cumReturn.shift(1)).fillna(1)
    
    return dayReturn, cumReturn, quantityDf

In [150]:
_,_, q = getRebalPortResultWithFee(closeDataSet=closeDataSet, totalAsset=10000000)
q

2012-01-31 00:00:00 2012-02-29 00:00:00
2012-02-29 00:00:00 2012-03-30 00:00:00
2012-03-30 00:00:00 2012-04-30 00:00:00
2012-04-30 00:00:00 2012-05-31 00:00:00
2012-05-31 00:00:00 2012-06-29 00:00:00
2012-06-29 00:00:00 2012-07-31 00:00:00
2012-07-31 00:00:00 2012-08-31 00:00:00
2012-08-31 00:00:00 2012-09-28 00:00:00
2012-09-28 00:00:00 2012-10-31 00:00:00
2012-10-31 00:00:00 2012-11-30 00:00:00
2012-11-30 00:00:00 2012-12-28 00:00:00
2012-12-28 00:00:00 2013-01-31 00:00:00
2013-01-31 00:00:00 2013-02-28 00:00:00
2013-02-28 00:00:00 2013-03-29 00:00:00
2013-03-29 00:00:00 2013-04-30 00:00:00
2013-04-30 00:00:00 2013-05-31 00:00:00
2013-05-31 00:00:00 2013-06-28 00:00:00
2013-06-28 00:00:00 2013-07-31 00:00:00
2013-07-31 00:00:00 2013-08-30 00:00:00
2013-08-30 00:00:00 2013-09-30 00:00:00
2013-09-30 00:00:00 2013-10-31 00:00:00
2013-10-31 00:00:00 2013-11-29 00:00:00
2013-11-29 00:00:00 2013-12-30 00:00:00
2013-12-30 00:00:00 2014-01-29 00:00:00
2014-01-29 00:00:00 2014-02-28 00:00:00
2014-02-28 00:00:00 2014-03-31 00:00:00
2014-03-31 00:00:00 2014-04-30 00:00:00
2014-04-30 00:00:00 2014-05-30 00:00:00
2014-05-30 00:00:00 2014-06-30 00:00:00
2014-06-30 00:00:00 2014-07-31 00:00:00
2014-07-31 00:00:00 2014-08-29 00:00:00
2014-08-29 00:00:00 2014-09-30 00:00:00
2014-09-30 00:00:00 2014-10-31 00:00:00
2014-10-31 00:00:00 2014-11-28 00:00:00
2014-11-28 00:00:00 2014-12-30 00:00:00
2014-12-30 00:00:00 2015-01-30 00:00:00
2015-01-30 00:00:00 2015-02-27 00:00:00
2015-02-27 00:00:00 2015-03-31 00:00:00
2015-03-31 00:00:00 2015-04-30 00:00:00
2015-04-30 00:00:00 2015-05-29 00:00:00
2015-05-29 00:00:00 2015-06-30 00:00:00
2015-06-30 00:00:00 2015-07-31 00:00:00
2015-07-31 00:00:00 2015-08-31 00:00:00
2015-08-31 00:00:00 2015-09-30 00:00:00
2015-09-30 00:00:00 2015-10-30 00:00:00
2015-10-30 00:00:00 2015-11-30 00:00:00
2015-11-30 00:00:00 2015-12-30 00:00:00
2015-12-30 00:00:00 2016-01-29 00:00:00
2016-01-29 00:00:00 2016-02-29 00:00:00
2016-02-29 00:00:00 2016-03-31 00:00:00
2016-03-31 00:00:00 2016-04-29 00:00:00
2016-04-29 00:00:00 2016-05-31 00:00:00
2016-05-31 00:00:00 2016-06-30 00:00:00
2016-06-30 00:00:00 2016-07-29 00:00:00
2016-07-29 00:00:00 2016-08-31 00:00:00
2016-08-31 00:00:00 2016-09-30 00:00:00
2016-09-30 00:00:00 2016-10-31 00:00:00
2016-10-31 00:00:00 2016-11-30 00:00:00
2016-11-30 00:00:00 2016-12-29 00:00:00
2016-12-29 00:00:00 2017-01-31 00:00:00
2017-01-31 00:00:00 2017-02-28 00:00:00
2017-02-28 00:00:00 2017-03-31 00:00:00
2017-03-31 00:00:00 2017-04-28 00:00:00
2017-04-28 00:00:00 2017-05-31 00:00:00
2017-05-31 00:00:00 2017-06-30 00:00:00
2017-06-30 00:00:00 2017-07-31 00:00:00
2017-07-31 00:00:00 2017-08-31 00:00:00
2017-08-31 00:00:00 2017-09-29 00:00:00
2017-09-29 00:00:00 2017-10-31 00:00:00
2017-10-31 00:00:00 2017-11-30 00:00:00
2017-11-30 00:00:00 2017-12-28 00:00:00
2017-12-28 00:00:00 2018-01-31 00:00:00
2018-01-31 00:00:00 2018-02-28 00:00:00
2018-02-28 00:00:00 2018-03-30 00:00:00
2018-03-30 00:00:00 2018-04-30 00:00:00
2018-04-30 00:00:00 2018-05-31 00:00:00
2018-05-31 00:00:00 2018-06-29 00:00:00
2018-06-29 00:00:00 2018-07-31 00:00:00
2018-07-31 00:00:00 2018-08-31 00:00:00
2018-08-31 00:00:00 2018-09-28 00:00:00
2018-09-28 00:00:00 2018-10-31 00:00:00
2018-10-31 00:00:00 2018-11-30 00:00:00
2018-11-30 00:00:00 2018-12-28 00:00:00
2018-12-28 00:00:00 2019-01-31 00:00:00
2019-01-31 00:00:00 2019-02-28 00:00:00
2019-02-28 00:00:00 2019-03-29 00:00:00
2019-03-29 00:00:00 2019-04-30 00:00:00
2019-04-30 00:00:00 2019-05-31 00:00:00
2019-05-31 00:00:00 2019-06-28 00:00:00
2019-06-28 00:00:00 2019-07-31 00:00:00
2019-07-31 00:00:00 2019-08-30 00:00:00
2019-08-30 00:00:00 2019-09-30 00:00:00
2019-09-30 00:00:00 2019-10-31 00:00:00
2019-10-31 00:00:00 2019-11-29 00:00:00
2019-11-29 00:00:00 2019-12-30 00:00:00
2019-12-30 00:00:00 2020-01-31 00:00:00
2020-01-31 00:00:00 2020-02-28 00:00:00
2020-02-28 00:00:00 2020-03-31 00:00:00
2020-03-31 00:00:00 2020-04-29 00:00:00
2020-04-29 00:00:00 2020-05-29 00:00:00
2020-05-29 00:00:00 2020-06-30 00:00:00
2020-06-30 00:00:00 2020-07-31 00:00:00
2020-07-31 00:00:00 2020-08-31 00:00:00
2020-08-31 00:00:00 2020-09-29 00:00:00
2020-09-29 00:00:00 2020-10-30 00:00:00
2020-10-30 00:00:00 2020-11-30 00:00:00
2020-11-30 00:00:00 2020-12-30 00:00:00
2020-12-30 00:00:00 2021-01-29 00:00:00
2021-01-29 00:00:00 2021-02-26 00:00:00
2021-02-26 00:00:00 2021-03-31 00:00:00
2021-03-31 00:00:00 2021-04-30 00:00:00
2021-04-30 00:00:00 2021-05-31 00:00:00
2021-05-31 00:00:00 2021-06-30 00:00:00
2021-06-30 00:00:00 2021-07-30 00:00:00
2021-07-30 00:00:00 2021-08-31 00:00:00
2021-08-31 00:00:00 2021-09-30 00:00:00
2021-09-30 00:00:00 2021-10-29 00:00:00
2021-10-29 00:00:00 2021-11-30 00:00:00
2021-11-30 00:00:00 2021-12-30 00:00:00
2021-12-30 00:00:00 2022-01-28 00:00:00
2022-01-28 00:00:00 2022-02-28 00:00:00
2022-02-28 00:00:00 2022-03-31 00:00:00
2022-03-31 00:00:00 2022-04-29 00:00:00
2022-04-29 00:00:00 2022-05-31 00:00:00
2022-05-31 00:00:00 2022-06-30 00:00:00
2022-06-30 00:00:00 2022-07-29 00:00:00
2022-07-29 00:00:00 2022-08-08 00:00:00

            stock   bond
Date
2012-01-31  229.0   99.0
2012-02-29  225.0  101.0
2012-03-30  225.0  101.0
2012-04-30  227.0  100.0
2012-05-31  238.0   96.0
...           ...    ...
2022-03-31  207.0  116.0
2022-04-29  208.0  115.0
2022-05-31  208.0  115.0
2022-06-30  220.0  109.0
2022-07-29  220.0  109.0

[127 rows x 2 columns]